--liquibase formatted sql

--changeset ShelterBotContributors:1
CREATE TABLE IF NOT EXISTS pets
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type  VARCHAR NOT NULL,
    name  VARCHAR NOT NULL,
    age   INTEGER NOT NULL,
    breed VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS users
(
    chat_id       BIGINT    NOT NULL PRIMARY KEY,
    name          VARCHAR,
    phone         VARCHAR,
    last_cmd      VARCHAR,
    registered_at TIMESTAMP NOT NULL,
    pet_id        BIGINT REFERENCES pets (id)
);
CREATE TABLE IF NOT EXISTS reports
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id     BIGINT    NOT NULL REFERENCES users (chat_id),
    photo_id    VARCHAR,
    text        VARCHAR,
    date_time   TIMESTAMP NOT NULL,
    is_approved BOOLEAN
);
